BACKBONE2D:
  YOLOv8:
    ver : x

    PRETRAIN:
      n : weights/backbone2D/YOLOv8/v8_n.pth
      s : weights/backbone2D/YOLOv8/v8_s.pth
      m : weights/backbone2D/YOLOv8/v8_m.pth
      l : weights/backbone2D/YOLOv8/v8_l.pth
      x : weights/backbone2D/YOLOv8/v8_x.pth

BACKBONE3D:

  MOBILENET:
    width_mult: 2.0

    PRETRAIN:
      width_mult_0.5x  : weights/backbone3D/mobilenet/kinetics_mobilenet_0.5x_RGB_16_best.pth
      width_mult_1.0x  : weights/backbone3D/mobilenet/kinetics_mobilenet_1.0x_RGB_16_best.pth
      width_mult_1.5x  : weights/backbone3D/mobilenet/kinetics_mobilenet_1.5x_RGB_16_best.pth
      width_mult_2.0x  : weights/backbone3D/mobilenet/kinetics_mobilenet_2.0x_RGB_16_best.pth

  MOBILENETv2:
    width_mult: 1.0

    PRETRAIN:
      width_mult_0.2x  : weights/backbone3D/mobilenetv2/kinetics_mobilenetv2_0.2x_RGB_16_best.pth
      width_mult_0.45x : weights/backbone3D/mobilenetv2/kinetics_mobilenetv2_0.45x_RGB_16_best.pth
      width_mult_0.7x  : weights/backbone3D/mobilenetv2/kinetics_mobilenetv2_0.7x_RGB_16_best.pth
      width_mult_1.0x  : weights/backbone3D/mobilenetv2/kinetics_mobilenetv2_1.0x_RGB_16_best.pth

  SHUFFLENET:
    width_mult: 2.0

    PRETRAIN:
      width_mult_0.5x  : weights/backbone3D/shufflenet/kinetics_shufflenet_0.5x_G3_RGB_16_best.pth
      width_mult_1.0x  : weights/backbone3D/shufflenet/kinetics_shufflenet_1.0x_G3_RGB_16_best.pth
      width_mult_1.5x  : weights/backbone3D/shufflenet/kinetics_shufflenet_1.5x_G3_RGB_16_best.pth
      width_mult_2.0x  : weights/backbone3D/shufflenet/kinetics_shufflenet_2.0x_G3_RGB_16_best.pth

  SHUFFLENETv2:
    width_mult: 2.0

    PRETRAIN:
      width_mult_0.25x : weights/backbone3D/shufflenetv2/kinetics_shufflenetv2_0.25x_RGB_16_best.pth
      width_mult_1.0x  : weights/backbone3D/shufflenetv2/kinetics_shufflenetv2_1.0x_RGB_16_best.pth
      width_mult_1.5x  : weights/backbone3D/shufflenetv2/kinetics_shufflenetv2_1.5x_RGB_16_best.pth
      width_mult_2.0x  : weights/backbone3D/shufflenetv2/kinetics_shufflenetv2_2.0x_RGB_16_best.pth
      
  I3D:
    PRETRAIN:
      default: weights/backbone3D/I3D/rgb_imagenet.pth
  
  RESNET:
    ver : 101

    PRETRAIN:
      ver_18 : weights/backbone3D/resnet/kinetics_resnet_18_RGB_16_best.pth
      ver_50 : weights/backbone3D/resnet/kinetics_resnet_50_RGB_16_best.pth
      ver_101: weights/backbone3D/resnet/kinetics_resnet_101_RGB_16_best.pth

  RESNEXT:
    ver : 101

    PRETRAIN:
      ver_101 : weights/backbone3D/resnext/resnext-101-kinetics.pth

LOSS:
  TAL:
    top_k  : 10
    alpha  : 0.5
    beta   : 6.0
    radius : 2.5
    soft_label : False

    scale_cls_loss : 0.5
    scale_box_loss : 7.5
    scale_dfl_loss : 1.5

  SIMOTA:
    top_k  : 10
    gamma  : 0.5
    radius : 2.5
    mode   : unbalance
    soft_label : True

    dynamic_k     : False 
    dynamic_top_k : 10

    scale_cls_loss : 0.5
    scale_box_loss : 5.0
    scale_dfl_loss : 0.5


config_path       : config/cf2/etri_config.yaml
dataset           : etri
loss              : tal
active_checker    : True
num_classes       : 55  # will be overridden dynamically by dataset based on actions discovered
backbone2D        : yolov8
backbone3D        : resnet
fusion_module     : CFAM
mode              : decoupled
interchannels     : [256, 256, 256]

# Set this to your previous checkpoint to fine-tune
pretrain_path     : checkpoint/avav2.2/O27/ema_epoch_9.pth

# ETRI data root (expects subfolders: RGB(P01-P20), JointCSV(P01-P20), BodyIndex(P01-P20))
data_root         : etri

img_size          : 224
clip_length       : 16
batch_size        : 8
num_workers       : 6
acc_grad          : 16
lr                : 0.00001
weight_decay      : 0.0005
max_step_warmup   : 500
adjustlr_schedule : [1, 2, 3, 4, 5]
max_epoch         : 9
lr_decay          : 0.5
save_folder       : weights/model_checkpoint
sampling_rate     : 1
label_map         : config/etri_idx2name_en.yaml

# ETRI dataset options
participants      : P01          # or comma-separated e.g. "P01,P02"
key_stride        : 1            # sample every N-th key frame from skeleton CSV
bbox_padding      : 0.15         # padding ratio around skeleton bbox
use_bodyindex_scale: true        # scale depth coords to RGB using BodyIndex PNG size
min_box_size_ratio : 0.05        # enforce minimum bbox size as ratio of frame
bbox_square        : false        # force square boxes for clearer viz
