idx2name:
  0: Eating with a spoon or fork
  1: Pouring a drink into a cup
  2: Taking medicine
  3: Drinking water or beverage
  4: Using the refrigerator (put in / take out food)
  5: Preparing vegetables
  6: Peeling fruit
  7: Heating food on the stove
  8: Cutting food on a cutting board
  9: Brushing teeth
  10: Washing hands
  11: Washing face
  12: Drying with a towel (body/hair)
  13: Applying cosmetics
  14: Applying lipstick
  15: Combing hair
  16: Drying hair with a hair dryer
  17: Putting on a top
  18: Taking off a top
  19: Putting on/off shoes
  20: Putting on/off glasses
  21: Doing the dishes
  22: Using a vacuum cleaner
  23: Wiping the floor with a cloth (on knees)
  24: Wiping a table with a dishcloth
  25: Cleaning windows or furniture
  26: Making and folding a blanket
  27: Hand-washing laundry
  28: Hanging laundry
  29: Looking around to find something
  30: Controlling TV with a remote
  31: Reading a book
  32: Reading a newspaper
  33: Writing
  34: Making or receiving a phone call
  35: Using a smartphone
  36: Typing on a computer keyboard
  37: Smoking
  38: Clapping
  39: Rubbing face with both hands
  40: Calisthenics (freehand exercise)
  41: Neck rotation exercise
  42: Self-massaging shoulders
  43: Bowing greeting
  44: Having a conversation
  45: Handshake
  46: Hugging
  47: Fighting each other
  48: Waving hand
  49: Beckoning (calling to come)
  50: Pointing with a finger
  51: Opening a door and entering
  52: Picking up litter
  53: Getting up from lying
  54: Going from standing to lying
