BACKBONE2D:
  YOLOv8:
    ver : x

    PRETRAIN:
      n : weights/backbone2D/YOLOv8/v8_n.pth
      s : weights/backbone2D/YOLOv8/v8_s.pth
      m : weights/backbone2D/YOLOv8/v8_m.pth
      l : weights/backbone2D/YOLOv8/v8_l.pth
      x : weights/backbone2D/YOLOv8/v8_x.pth

BACKBONE3D:

  I3D:
    PRETRAIN:
      default: weights/backbone3D/I3D/rgb_imagenet.pth

LOSS:
  TAL:
    top_k  : 10
    alpha  : 0.5
    beta   : 6.0
    radius : 2.5
    soft_label : False

    scale_cls_loss : 0.5
    scale_box_loss : 7.5
    scale_dfl_loss : 1.5

config_path       : config/cf2/etri_config.yaml
dataset           : etri
loss              : tal
active_checker    : True
num_classes       : 55  # will be overridden dynamically by dataset based on actions discovered
backbone2D        : yolov8
backbone3D        : i3d
fusion_module     : CFAM
mode              : decoupled
interchannels     : [256, 256, 256]

# Set this to your previous checkpoint to fine-tune
pretrain_path     : checkpoint/avav2.2/O27/ema_epoch_9.pth

# ETRI data root (expects subfolders: RGB(P01-P20), JointCSV(P01-P20), BodyIndex(P01-P20))
data_root         : etri

img_size          : 224
clip_length       : 16
batch_size        : 8
num_workers       : 6
acc_grad          : 16
lr                : 0.0001
weight_decay      : 0.0005
max_step_warmup   : 500
adjustlr_schedule : [1, 2, 3, 4, 5]
max_epoch         : 7
lr_decay          : 0.5
save_folder       : weights/model_checkpoint
sampling_rate     : 1

# ETRI dataset options
participants      : P01          # or comma-separated e.g. "P01,P02"
key_stride        : 1            # sample every N-th key frame from skeleton CSV
bbox_padding      : 0.15         # padding ratio around skeleton bbox
use_bodyindex_scale: true        # scale depth coords to RGB using BodyIndex PNG size
